pluginName = SonarQ in EDT
providerName = Jimmo910
preferencePageName = SonarQube
propertyPageName = SonarQube
viewCategoryName = SonarQube
issuesViewName = SonarQube Issues
markerName = SonarQube Issue
