featureName = SonarQ in EDT
providerName = Jimmo910
description = SonarQube issues for 1C:Enterprise (BSL) code right inside EDT.
license = This feature is made available under the Eclipse Public License 2.0.
